{% set version = "5.5.0" %}

package:
  name: nbformat
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nbformat/nbformat-{{ version }}.tar.gz
  sha256: 9ebe30e6c3b3e5b47d39ff0a3897a1acf523d2bfafcb4e2d04cdb70f8a66c507

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jupyter-trust = nbformat.sign:TrustNotebookApp.launch_instance

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - jsonschema >=2.6
    - jupyter_core
    - python >=3.7
    - python-fastjsonschema
    - traitlets >=5.1

test:
  source_files:
    - tests
  commands:
    - pip check
    - jupyter trust --version
    - jupyter-trust --help
    - pytest -vv --cov nbformat --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under 79
  requires:
    - pip
    - pytest
    - pytest-cov
    - testpath
  imports:
    - nbformat

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  summary: The Jupyter Notebook format
  license_file: COPYING.md
  doc_url: https://nbformat.readthedocs.io
  dev_url: https://github.com/jupyter/nbformat

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - takluyver
    - ocefpaf
    - mpacer
    - bollwyvl
